<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\FluxRAM.ico</ApplicationIcon>
    <RootNamespace>FluxRAM.App</RootNamespace>
    <AssemblyName>FluxRAM.App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\FluxRAM.ico" Link="FluxRAM.ico" />
    <Resource Include="Assets\PurchasePro\*.jpg" />
    <ProjectReference Include="..\FluxRAM.Core\FluxRAM.Core.csproj" />
  </ItemGroup>
</Project>
